services:
  web:
    image: node:20                        # bruker node versjon 20
    working_dir: /app                     # arbeidsmappe inne i containeren
    volumes:
      - C:/Eksamen:/app                   # kobler prosjektmappen til containeren
    command: sh -c "rm -rf node_modules && npm install && node kildekode/index.js" # installerer pakker og starter serveren
    ports:
      - "3000:3000"                       # port 3000 er åpen for alle (kundeside)
    networks:
      - public                            # koblet til public nettverket

  admin:
    image: node:20                        # bruker node versjon 20
    working_dir: /app                     # arbeidsmappe inne i containeren
    volumes:
    - C:/Eksamen:/app                        # kobler prosjektmappen til containeren
    command: sh -c "rm -rf node_modules && npm install && node kildekode/index.js" # installerer pakker og starter serveren
    ports:
      - "127.0.0.1:3001:3000"            # kun tilgjengelig lokalt, ikke utenfra (brannmur)
    networks:
      - internal                          # koblet til internal-nettverket

networks:
  public:
    driver: bridge                        # vanlig nettverk, tilgjengelig utenfra
  internal:
    driver: bridge                        # internt nettverk
    internal: true                        # blokkerer all ekstern trafikk